services:

  database:
    build:
      context: .
      dockerfile: Dockerfile-db
    
    ports:
      - 5432:5432
    
    restart: always

    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: exampledb

    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    
  
  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080

